### ISSUE TITLE
Determine if we should get rid of `deploy-site` ruby script

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/jenkins-infra#2356]
Not sure at all but I'm wondering if we shouldn't also get rid of the ruby script https://github.com/jenkins-infra/jenkins-infra/blob/cdc715088a1fddf3f55df2d3397b096d96b15928/dist/profile/files/staticsite/deploy-site

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/jenkins-infra/issues/2355#issuecomment-1229931332_

**Comment by dduportal** [comment]
Absolutely!

- Current deployment of jenkins.io (or any other website) is done through a pipeline step, only run on a trusted/private Jenkins controller (because of credentials) into an Azure bucket file (mounted and served by a webserver in production), such as https://github.com/jenkins-infra/jenkins.io/blob/master/Jenkinsfile#L101
- Contributors can use GH pages: https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#deploying-jenkinsio-on-github-pages

So go go go for removing this script!
